import { AIPRow, SectorColors } from "./types";

export const DUMMY_DATA: AIPRow[] = [
  {
    id: 1,
    sector: "Social Services",
    aipCode: "SS-001",
    description: "Construction of Barangay Health Center",
    department: "City Health Office",
    startDate: "Jan 2027",
    endDate: "Jun 2027",
    outputs: "1 Health Center constructed",
    funding: "General Fund",
    ps: 500,
    mooe: 1200,
    fe: 0,
    co: 8300,
    total: 10000,
    ccAdaptation: 2000,
    ccMitigation: 500,
    ccCode: "A",
  },
  {
    id: 2,
    sector: "Social Services",
    aipCode: "SS-002",
    description: "Livelihood Training Program for Women",
    department: "CSWDO",
    startDate: "Feb 2027",
    endDate: "Nov 2027",
    outputs: "500 women trained",
    funding: "General Fund",
    ps: 800,
    mooe: 2200,
    fe: 0,
    co: 0,
    total: 3000,
    ccAdaptation: 0,
    ccMitigation: 0,
    ccCode: "",
  },
  {
    id: 3,
    sector: "Social Services",
    aipCode: "SS-003",
    description: "Senior Citizen Assistance Program",
    department: "CSWDO",
    startDate: "Jan 2027",
    endDate: "Dec 2027",
    outputs: "2,000 seniors assisted",
    funding: "Special Fund",
    ps: 400,
    mooe: 1600,
    fe: 0,
    co: 0,
    total: 2000,
    ccAdaptation: 0,
    ccMitigation: 0,
    ccCode: "",
  },
  {
    id: 4,
    sector: "Infrastructure",
    aipCode: "INF-001",
    description: "Road Concreting - Barangay San Isidro",
    department: "City Engineering Office",
    startDate: "Mar 2027",
    endDate: "Sep 2027",
    outputs: "2.5 km road concreted",
    funding: "General Fund",
    ps: 1200,
    mooe: 3800,
    fe: 0,
    co: 25000,
    total: 30000,
    ccAdaptation: 5000,
    ccMitigation: 1000,
    ccCode: "A",
  },
  {
    id: 5,
    sector: "Infrastructure",
    aipCode: "INF-002",
    description: "Flood Control & Drainage Improvement",
    department: "City Engineering Office",
    startDate: "Apr 2027",
    endDate: "Dec 2027",
    outputs: "3 drainage channels improved",
    funding: "DPWH Subsidy",
    ps: 900,
    mooe: 2100,
    fe: 0,
    co: 42000,
    total: 45000,
    ccAdaptation: 20000,
    ccMitigation: 3000,
    ccCode: "A/M",
  },
  {
    id: 6,
    sector: "Infrastructure",
    aipCode: "INF-003",
    description: "Solar Street Lighting Installation",
    department: "City Engineering Office",
    startDate: "May 2027",
    endDate: "Aug 2027",
    outputs: "200 solar lights installed",
    funding: "General Fund",
    ps: 300,
    mooe: 700,
    fe: 0,
    co: 9000,
    total: 10000,
    ccAdaptation: 0,
    ccMitigation: 8000,
    ccCode: "M",
  },
  {
    id: 7,
    sector: "Economic Development",
    aipCode: "ED-001",
    description: "Public Market Renovation",
    department: "City Market Authority",
    startDate: "Jun 2027",
    endDate: "Dec 2027",
    outputs: "1 market renovated",
    funding: "General Fund",
    ps: 600,
    mooe: 1400,
    fe: 0,
    co: 18000,
    total: 20000,
    ccAdaptation: 0,
    ccMitigation: 0,
    ccCode: "",
  },
  {
    id: 8,
    sector: "Economic Development",
    aipCode: "ED-002",
    description: "MSME Technology & Business Development",
    department: "CITO",
    startDate: "Jan 2027",
    endDate: "Dec 2027",
    outputs: "300 MSMEs assisted",
    funding: "General Fund",
    ps: 700,
    mooe: 2800,
    fe: 500,
    co: 0,
    total: 4000,
    ccAdaptation: 0,
    ccMitigation: 0,
    ccCode: "",
  },
  {
    id: 9,
    sector: "Environment",
    aipCode: "ENV-001",
    description: "Urban Greening & Tree Planting Program",
    department: "City Environment Office",
    startDate: "Jan 2027",
    endDate: "Dec 2027",
    outputs: "5,000 trees planted",
    funding: "Special Fund",
    ps: 300,
    mooe: 700,
    fe: 0,
    co: 0,
    total: 1000,
    ccAdaptation: 500,
    ccMitigation: 400,
    ccCode: "A/M",
  },
  {
    id: 10,
    sector: "Environment",
    aipCode: "ENV-002",
    description: "Materials Recovery Facility Expansion",
    department: "City Environment Office",
    startDate: "Feb 2027",
    endDate: "Oct 2027",
    outputs: "1 MRF expanded (500 sqm)",
    funding: "General Fund",
    ps: 400,
    mooe: 600,
    fe: 0,
    co: 7000,
    total: 8000,
    ccAdaptation: 0,
    ccMitigation: 6000,
    ccCode: "M",
  },
];

export const NUMERIC_FIELDS: (keyof AIPRow)[] = [
  "ps",
  "mooe",
  "fe",
  "co",
  "total",
  "ccAdaptation",
  "ccMitigation",
];

export const DEFAULT_SECTORS = [
  "Social Services",
  "Infrastructure",
  "Economic Development",
  "Environment",
];

export const SECTOR_COLORS: Record<string, SectorColors> = {
  "Social Services": {
    bg: "bg-blue-50",
    badge: "bg-blue-100 text-blue-800",
    border: "border-blue-200",
  },
  Infrastructure: {
    bg: "bg-amber-50",
    badge: "bg-amber-100 text-amber-800",
    border: "border-amber-200",
  },
  "Economic Development": {
    bg: "bg-green-50",
    badge: "bg-green-100 text-green-800",
    border: "border-green-200",
  },
  Environment: {
    bg: "bg-emerald-50",
    badge: "bg-emerald-100 text-emerald-800",
    border: "border-emerald-200",
  },
};

export const EMPTY_ROW = (): AIPRow => ({
  id: Date.now(),
  sector: "",
  aipCode: "",
  description: "",
  department: "",
  startDate: "",
  endDate: "",
  outputs: "",
  funding: "",
  ps: 0,
  mooe: 0,
  fe: 0,
  co: 0,
  total: 0,
  ccAdaptation: 0,
  ccMitigation: 0,
  ccCode: "",
});
